version: "3.7"
services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - network
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rlaghwns1!
      MYSQL_DATABASE: A202DB
      MYSQL_USER: A202user
      MYSQL_PASSWORD: ekdrnwkd1!
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./collectstatic:/data/static
    ports:
      - 80:80
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: django
    networks:
      - network
    volumes:
      - ./static:/djangoproject/static
    command: >
      bash -c "
      gunicorn A202.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - mysql
networks:
  network:
      driver: bridge

volumes:
  mysql:
